### ISSUE TITLE
closing the keyboard  searched  text suggestions are gone after that it show from start?(i think it might be overlay issue)

### ISSUE THREAD

**Issue by sabari7320** [maheshj01/searchfield#187] opened 2024-11-06 09:45 UTC
https://drive.google.com/file/d/132iZYWgLzDNMllLGyOlkA15SayzkrcZe/view

**Comment by maheshj01** [comment] 2024-11-10 18:16
@sabari7320 Can you add more details about the issue, This template was provided to help better investigate the issue.

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

[ ] By clicking this checkbox, I confirm I am using the latest version of the package found on [pub.dev/searchfield](https://pub.dev/packages/searchfield)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual behavior**
What you actually saw instead of the expected behavior.

**Screenshots**
If applicable, add screenshots to help explain your problem.


**Code sample**
<details>
<summary>Show code sample</summary>

```dart  
Paste minimal and complete code sample here to investigate the issue. 
```
</details>

**Additional context**
Add any other context about the problem here.

```

**Comment by sabari7320** [comment] 2024-11-20 03:08
https://github.com/user-attachments/assets/856c902f-87fe-439d-b568-8081b752675c

could you please check this video @maheshj01

**Comment by maheshj01** [comment] 2024-11-22 00:20
Closing as duplicate of #190 please follow up on that issue.

**Closed by maheshj01** 2024-11-22 00:20 UTC
Labels: waiting for author, in triage
