### ISSUE TITLE
The superclass, 'InputDecoration', has no unnamed constructor that takes no arguments.

### ISSUE THREAD

**Issue by Princewil** [maheshj01/searchfield#200] opened 2024-12-22 09:21 UTC
<img width="1136" alt="Screenshot 2024-12-22 at 10 20 55" src="https://github.com/user-attachments/assets/6d2c1a86-800b-43c1-b9f4-4683fe0fb3bf" />

Xcode build failed because of the above. I am using the latest package

**Comment by Princewil** [comment] 2024-12-22 09:48
Although I fixed it [here](https://github.com/Princewil/searchfield.git). 
I will probably request a pull request

**Comment by maheshj01** [comment] 2024-12-23 12:36
Hi @Princewil, please share the complete error log and the output of `flutter doctor -v`  and the version of searchfield you are using to better understand the issue.

**Comment by Princewil** [comment] 2024-12-24 03:05
I have solved the problem already and created a pull request. Check it out

**Comment by maheshj01** [comment] 2024-12-24 04:33
@Princewil Thanks for your Pr. Unfortunately I can't review it unless I know what the issue is. To investigate further, I will need the complete error log, output of `flutter doctor -v` and the version of searchfield that you are using.

**Comment by ayjayem** [comment] 2024-12-24 20:58
Hi there -- I am also experiencing this exact issue. I am using searchfield version 1.2.1 with the same error @maheshj01 notes: 

Could not build the precompiled application for the device.
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/searchfield-1.2.1/lib/src/input_decoration.dart:62:3: Error: The superclass, 'InputDecoration', has no unnamed constructor that takes no arguments.

**Comment by Princewil** [comment] 2024-12-24 21:05
@ayjayem I forked the repo and fixed the issue. If it's urgent you can check the pull request section for the repo.

While we await @maheshj01 to fix the issue or merge the pull request.

**Comment by Princewil** [comment] 2024-12-24 21:11
> @Princewil Thanks for your Pr. Unfortunately I can't review it unless I know what the issue is. To investigate further, I will need the complete error log, output of `flutter doctor -v` and the version of searchfield that you are using.

@maheshj01 I'm so sorry, I don't have the free time to do this at the moment. However, to reproduce the error "run flutter build ios".

**Comment by maheshj01** [comment] 2024-12-24 21:12
@Princewil What version of flutter arre you using?

**Comment by Princewil** [comment] 2024-12-24 21:15
@maheshj01 v3.24.3

**Comment by maheshj01** [comment] 2024-12-24 21:20
Thats the reason for this error, This is mentioned in the changelog.

> *Note: To use Searchfield 1.2.1 you would need flutter 3.27.0 or greater*

**Comment by Princewil** [comment] 2024-12-24 22:07
Thanks for the clarification.

But I think it should have been stated on the readme section. People rearly visit the Changelog section.

**Comment by maheshj01** [comment] 2024-12-24 22:37
Closing as there is no action required for this fix. Inorder to use `Searchfield 1.2.1 ` and above You must upgrade to flutter 3.27.0 and above. I plan to avoid this situation in the future releases by adding a min flutter sdk constraint.

**Closed by maheshj01** 2024-12-24 22:37 UTC
Labels: waiting for author, in triage
