### ISSUE TITLE
keyboard  issue while closing 

### ISSUE THREAD

**Issue by sabari7320** [maheshj01/searchfield#190] opened 2024-11-21 07:40 UTC
**Describe the bug**
When I select a value from the dropdown and then close the keyboard, the selected value disappears, and the dropdown list resets to its initial state

```dart
SearchField(
autovalidateMode: AutovalidateMode.onUserInteraction,
onTapOutside: null,
        focusNode: _otherTextFieldFocusNode,
          suggestionStyle: TextStyle(decoration: TextDecoration.none),
          searchInputDecoration: SearchInputDecoration(
            border: InputBorder.none,
            labelText: 'State',
            enabledBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Colors.grey),
                borderRadius: BorderRadius.circular(10)),
            focusedBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Colors.grey),
                borderRadius: BorderRadius.circular(10)),
            disabledBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Colors.grey),
                borderRadius: BorderRadius.circular(10)),
            errorBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Colors.red),
                borderRadius: BorderRadius.circular(10)),
            focusedErrorBorder:OutlineInputBorder(
                borderSide: BorderSide(color: Colors.red),
                borderRadius: BorderRadius.circular(10)),
            hintStyle: TextStyle(color: Colors.black),
            contentPadding: const EdgeInsets.symmetric(vertical: 1.0, horizontal: 15),
          ),

          onSuggestionTap: (selectedValue) {
            print("Selected state: ${selectedValue.item}");
            stateController.text = selectedValue.item!;
            fetchCityList(countryController.text, selectedValue.item!);
            FocusScope.of(context).unfocus();
          },
          suggestions: stateList.isEmpty
          ? [SearchFieldListItem("No state available", child: Text("No state available"))]
              :stateList.map((state) => SearchFieldListItem(
            state,
            item: state,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(state),
            ),
          ))
              .toList(),
          itemHeight: 55,
          maxSuggestionsInViewPort: 4,
          controller: stateController,
          validator: (selectedValue) {
            if (selectedValue == null || !stateList.contains(selectedValue)) {
              return 'Please select State';
            }
            return null;
          },
        ),

```

https://github.com/user-attachments/assets/a47c1552-0ca4-45dd-978d-83526076b2ca

**Comment by maheshj01** [comment] 2024-11-22 00:23
Hi @sabari7320, 
I tried to reproduce the bug using the below code sample, But I am unable to reproduce it. Please provide more details
1. version of searchfield
2. output of `flutter doctor -v`
3. is this reproducible on a specific device or all devices?
4. is this reproducible in debug/release or both

It would be great if you can try to modify the below code sample and provide a reproducible code sample with steps to reproduce the issue.
 
<details>
<summary>code sample</summary>

```dart
// import 'package:example/pagination.dart';
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      theme: ThemeData(
        colorSchemeSeed: Colors.indigo,
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      home: SearchFieldSample(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class SearchFieldSample extends StatefulWidget {
  const SearchFieldSample({Key? key}) : super(key: key);

  @override
  State<SearchFieldSample> createState() => _SearchFieldSampleState();
}

class _SearchFieldSampleState extends State<SearchFieldSample> {
  @override
  void initState() {
    suggestions = [
      'United States',
      'Germany',
      'Canada',
      'United Kingdom',
      'France',
      'Italy',
      'Spain',
      'Australia',
      'India',
      'China',
      'Japan',
      'Brazil',
      'South Africa',
      'Mexico',
      'Argentina',
      'Russia',
      'Indonesia',
      'Turkey',
      'Saudi Arabia',
      'Nigeria',
      'Egypt',
    ];
    selected = suggestions[0];
    super.initState();
  }

  int suggestionsCount = 12;
  final _otherTextFieldFocusNode = FocusNode();
  final TextEditingController searchController = TextEditingController();
  var suggestions = <String>[];
  int counter = 0;
  var selected = '';
  @override
  Widget build(BuildContext context) {
    Widget searchChild(x, {bool isSelected = false}) => Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12),
          child: Text(x,
              style: TextStyle(
                  fontSize: 18,
                  color: isSelected ? Colors.green : Colors.black)),
        );
    return Scaffold(
        appBar: AppBar(title: Text('Searchfield Demo')),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ListView(
            children: [
              SearchField(
                autovalidateMode: AutovalidateMode.onUserInteraction,
                onTapOutside: null,
                focusNode: _otherTextFieldFocusNode,
                suggestionStyle: TextStyle(decoration: TextDecoration.none),
                searchInputDecoration: SearchInputDecoration(
                  border: InputBorder.none,
                  labelText: 'State',
                  enabledBorder: OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.grey),
                      borderRadius: BorderRadius.circular(10)),
                  focusedBorder: OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.grey),
                      borderRadius: BorderRadius.circular(10)),
                  disabledBorder: OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.grey),
                      borderRadius: BorderRadius.circular(10)),
                  errorBorder: OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.red),
                      borderRadius: BorderRadius.circular(10)),
                  focusedErrorBorder: OutlineInputBorder(
                      borderSide: BorderSide(color: Colors.red),
                      borderRadius: BorderRadius.circular(10)),
                  hintStyle: TextStyle(color: Colors.black),
                  contentPadding:
                      const EdgeInsets.symmetric(vertical: 1.0, horizontal: 15),
                ),
                onSuggestionTap: (selectedValue) {},
                suggestions: suggestions.isEmpty
                    ? [
                        SearchFieldListItem("No state available",
                            child: Text("No state available"))
                      ]
                    : suggestions
                        .map((state) => SearchFieldListItem(
                              state,
                              item: state,
                              child: Padding(
                                padding: const EdgeInsets.all(8.0),
                                child: Text(state),
                              ),
                            ))
                        .toList(),
                itemHeight: 55,
                maxSuggestionsInViewPort: 4,
                validator: (selectedValue) {
                  if (selectedValue == null ||
                      !suggestions.contains(selectedValue)) {
                    return 'Please select State';
                  }
                  return null;
                },
              ),
            ],
          ),
        ));
  }
}

```
</details>

**Comment by sunilpandit2** [comment] 2024-11-23 12:15
i am facing same issue

**Comment by maheshj01** [comment] 2024-11-23 21:40
@sunilpandit2 Can you provide the information [requested above](https://github.com/maheshj01/searchfield/issues/190#issuecomment-2492621038)? It will help me investigate the issue

**Comment by sabari7320** [comment] 2024-11-25 08:28
the latest version, it's working fine.

**Comment by maheshj01** [comment] 2024-11-25 13:48
@sabari7320  can you provide [this info ](https://github.com/maheshj01/searchfield/issues/190#issuecomment-2492621038)?

**Comment by maheshj01** [comment] 2024-11-25 20:28
@sabari7320  Can you try the latest release [v1.1.9](https://pub.dev/packages/searchfield/changelog)

**Comment by maheshj01** [comment] 2024-11-29 00:19
@sabari7320 Before I merge #191 Can you try  this out on your end and see if this also fixes your issue?

```yaml
 searchfield:
    git:
      url: https://github.com/maheshmnj/searchfield.git
      ref: breaking-design
```

**Comment by sabari7320** [comment] 2024-11-29 03:43
sure i will check it and let you know the output

**Comment by maheshj01** [comment] 2024-11-29 04:20
Thanks you can also try master branch,  I have merged that PR

```dart
 searchfield:
    git:
      url: https://github.com/maheshmnj/searchfield.git
      ref: master
```

**Comment by maheshj01** [comment] 2024-11-29 04:30
copied from : https://github.com/maheshj01/searchfield/issues/191#issuecomment-2507052784

> The issue is still present. Steps to reproduce the error:
>
> 1)Search for something.
2.)Related values appear.
3.)Click the close button.
4.)The full list of values appears again from the beginning.


@sabari7320 I am unable to reproduce it on my end, Can you reproduce it with this code sample or provide a reproducible code?

https://github.com/user-attachments/assets/5b787682-c873-46b3-ac31-55324bf77e13

<details>
<summary>code sample</summary>

```dart
// import 'package:example/pagination.dart';
import 'package:flutter/material.dart';
import 'package:searchfield/searchfield.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter App',
      theme: ThemeData(
        colorSchemeSeed: Colors.indigo,
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.blue,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      home: SearchFieldSample(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class SearchFieldSample extends StatefulWidget {
  const SearchFieldSample({Key? key}) : super(key: key);

  @override
  State<SearchFieldSample> createState() => _SearchFieldSampleState();
}

class _SearchFieldSampleState extends State<SearchFieldSample> {
  @override
  void initState() {
    suggestions = [
      'United States',
      'Germany',
      'Canada',
      'United Kingdom',
      'France',
      'Italy',
      'Spain',
      'Australia',
      'India',
      'China',
      'Japan',
      'Brazil',
      'South Africa',
      'Mexico',
      'Argentina',
      'Russia',
      'Indonesia',
      'Turkey',
      'Saudi Arabia',
      'Nigeria',
      'Egypt',
    ];
    super.initState();
  }

  var suggestions = <String>[];
  var selectedValue = null;
  @override
  Widget build(BuildContext context) {
    Widget searchChild(x, {bool isSelected = false}) => Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12),
          child: Text(x,
              style: TextStyle(
                  fontSize: 18,
                  color: isSelected ? Colors.green : Colors.black)),
        );
    return Scaffold(
        appBar: AppBar(title: Text('Searchfield Demo')),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ListView(
            children: [
              SearchField(
                suggestionDirection: SuggestionDirection.flex,
                onSearchTextChanged: (query) {
                  final filter = suggestions
                      .where((element) =>
                          element.toLowerCase().contains(query.toLowerCase()))
                      .toList();
                  return filter
                      .map((e) =>
                          SearchFieldListItem<String>(e, child: searchChild(e)))
                      .toList();
                },
                selectedValue: selectedValue,
                autovalidateMode: AutovalidateMode.onUserInteraction,
                validator: (value) {
                  if (value == null || !suggestions.contains(value.trim())) {
                    return 'Enter a valid country name';
                  }
                  return null;
                },
                maxSuggestionsInViewPort: 10,
                onSubmit: (x) {},
                autofocus: false,
                key: const Key('searchfield'),
                hint: 'Search by country name',
                itemHeight: 50,
                scrollbarDecoration: ScrollbarDecoration(
                  thickness: 12,
                  radius: Radius.circular(6),
                  trackColor: Colors.grey,
                  trackBorderColor: Colors.red,
                  thumbColor: Colors.orange,
                ),
                suggestionStyle:
                    const TextStyle(fontSize: 18, color: Colors.black),
                suggestionItemDecoration: BoxDecoration(
                  // color: Colors.grey[100],
                  // borderRadius: BorderRadius.circular(10),
                  border: Border(
                    bottom: BorderSide(
                      color: Colors.grey.shade200,
                      width: 1,
                    ),
                  ),
                ),
                searchInputDecoration: SearchInputDecoration(
                  searchStyle: TextStyle(fontSize: 18, color: Colors.black),
                  hintStyle: TextStyle(fontSize: 18, color: Colors.grey),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: const BorderSide(
                      width: 1,
                      color: Colors.orange,
                      style: BorderStyle.solid,
                    ),
                  ),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: const BorderSide(
                      width: 1,
                      color: Colors.black,
                      style: BorderStyle.solid,
                    ),
                  ),
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 20,
                  ),
                ),
                suggestionsDecoration: SuggestionDecoration(
                    // border: Border.all(color: Colors.orange),
                    elevation: 8.0,
                    selectionColor: Colors.grey.shade100,
                    hoverColor: Colors.purple.shade100,
                    gradient: LinearGradient(
                      colors: [
                        Color(0xfffc466b),
                        Color.fromARGB(255, 103, 128, 255)
                      ],
                      stops: [0.25, 0.75],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: BorderRadius.only(
                      bottomLeft: Radius.circular(10),
                      bottomRight: Radius.circular(10),
                    )),
                suggestions: suggestions
                    .map((e) =>
                        SearchFieldListItem<String>(e, child: searchChild(e)))
                    .toList(),
                suggestionState: Suggestion.expand,
                onSuggestionTap: (SearchFieldListItem<String> x) {
                  setState(() {
                    selectedValue = x;
                  });
                },
              ),
            ],
          ),
        ));
  }
}
``` 
</details>

**Comment by sabari7320** [comment] 2024-11-29 05:11
![Uploading Screenshot 2024-11-29 104100.png…]()

**Comment by sabari7320** [comment] 2024-11-29 05:12
![Screenshot 2024-11-29 104100](https://github.com/user-attachments/assets/cae42872-212b-470f-8793-b4d232806392)
Error is displayed can you check it once

**Comment by maheshj01** [comment] 2024-11-29 06:40
@sabari7320 
Try 'flutter clean' and 'flutter pub get'
After you have added this in pubspec.yaml

```
searchfield: git: url: https://github.com/maheshmnj/searchfield.git ref: master
```


Currently on my phone

**Comment by maheshj01** [comment] 2024-11-29 06:47
See this on how to add a dependency from GitHub

https://stackoverflow.com/a/54023220

**Comment by sabari7320** [comment] 2024-11-29 07:23
Thank you so much, bro! It’s working perfectly now. I really appreciate your guidance and instant replies. Your help made all the difference, and I’m truly grateful for your support in getting this fixed. 🙏

**Comment by maheshj01** [comment] 2024-11-29 08:38
Glad to hear that, I will publish the new version on pub.dev. Closing as fixed.

**Closed by maheshj01** 2024-11-29 08:38 UTC
Labels: waiting for author, in triage
